# Usa a imagem oficial do Node.js na versão 18
FROM node:18-alpine

# Define o diretório de trabalho dentro do container
WORKDIR /app

# Copia os arquivos de configuração para aproveitar o cache
COPY package*.json ./

# Instala as dependências
RUN npm install

# Copia o restante dos arquivos da aplicação
COPY . .

# Expõe a porta 3000 do container
EXPOSE 3000

# Comando para iniciar a aplicação
CMD [ "node", "server.js" ]
